from flask import Flask, render_template, jsonify, request
import json
from datetime import datetime
import random
import pickle
import numpy as np

app = Flask(__name__)

# Sample data - laptops with detailed specifications
sample_laptops = [
    {"id": 1, "brand": "TechCorp", "model": "Innovate 15", "processor": "Intel Core i7", "ram": 16, "storage": 512, "screen_size": 15.6, "rating": 4.7, "price": 1299},
    {"id": 2, "brand": "ProTech", "model": "Creator X", "processor": "AMD Ryzen 9", "ram": 32, "storage": 1024, "screen_size": 16.0, "rating": 4.9, "price": 2499},
    {"id": 3, "brand": "EduBook", "model": "Learn 13", "processor": "Intel Core i5", "ram": 8, "storage": 256, "screen_size": 13.3, "rating": 4.5, "price": 799},
    {"id": 4, "brand": "GamerZ", "model": "Beast Pro", "processor": "Intel Core i9", "ram": 32, "storage": 2048, "screen_size": 17.3, "rating": 4.8, "price": 3199},
    {"id": 5, "brand": "TechCorp", "model": "Innovate 14", "processor": "AMD Ryzen 7", "ram": 16, "storage": 512, "screen_size": 14.0, "rating": 4.6, "price": 1150},
    {"id": 6, "brand": "ProTech", "model": "Creator Z", "processor": "Intel Core i7", "ram": 16, "storage": 1024, "screen_size": 15.6, "rating": 4.7, "price": 1899},
    {"id": 7, "brand": "TravelLite", "model": "Air 13", "processor": "Intel Core i5", "ram": 8, "storage": 512, "screen_size": 13.3, "rating": 4.5, "price": 999},
    {"id": 8, "brand": "GamerZ", "model": "Beast Lite", "processor": "AMD Ryzen 5", "ram": 16, "storage": 512, "screen_size": 15.6, "rating": 4.4, "price": 1099}
]

# In a real application, these files would be generated by a separate model training script.
# For this example, we assume 'preprocessor.pkl' and 'model.pkl' exist.
try:
    with open('preprocessor.pkl', 'rb') as f:
        preprocessor = pickle.load(f)

    with open('model.pkl', 'rb') as f:
        model = pickle.load(f)
except FileNotFoundError:
    print("WARNING: 'preprocessor.pkl' or 'model.pkl' not found. The /api/predict endpoint will fail.")
    preprocessor, model = None, None

@app.route('/')
def index():
    return render_template('index.html')

@app.route('/api/laptops')
def get_laptops():
    # Advanced filtering
    query_params = request.args
    filtered_laptops = sample_laptops

    if 'brand' in query_params:
        brands = query_params.get('brand').split(',')
        filtered_laptops = [l for l in filtered_laptops if l['brand'] in brands]
    
    if 'min_ram' in query_params:
        min_ram = int(query_params.get('min_ram'))
        filtered_laptops = [l for l in filtered_laptops if l['ram'] >= min_ram]

    if 'processor' in query_params:
        processors = query_params.get('processor').lower().split(',')
        filtered_laptops = [l for l in filtered_laptops if any(p.strip() in l['processor'].lower() for p in processors)]

    return jsonify(filtered_laptops)

@app.route('/api/predict', methods=['POST'])
def predict_price():
    if not model or not preprocessor:
        return jsonify({'error': 'Model not loaded'}), 500

    features = request.get_json()
    
    # Create a feature array in the correct order for the model
    # This order must match the training data
    feature_array = np.array([[
        features.get('brand', 'Unknown'),
        features.get('processor', 'Unknown'),
        features.get('ram', 8),
        features.get('storage', 256),
        features.get('screen_size', 15.6),
        features.get('rating', 4.5)
    ]])

    # Preprocess the features
    processed_features = preprocessor.transform(feature_array)
    
    # Make prediction
    prediction = model.predict(processed_features)
    
    return jsonify({'predicted_price': round(prediction[0], 2)})

if __name__ == '__main__':
    app.run(debug=True)